### ISSUE TITLE
DNDHELP-2107 Find a way to indicate that we don't always trust the 360Link API for specific link levels, on specific platforms

### ISSUE THREAD

**Issue by bertrama** [mlibrary/mgetit#84]
Should be in a configuration file.

Because platforms fall under multiple DBIDs, we probably want to take those as a list.

Maybe:
```yaml
ignore:
  - db:
      - DBID1
      - DBID2
      -  ... etc ...
    level:
       - journal
       - volume
       - ... etc ...
```
